# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Home"
pageRef = "index"
weight = 10

[[main]]
name = "Online Entry"
pageRef = "online-entry"
weight = 20

[[main]]
name = "Patterns"
pageRef = "patterns"
weight = 30

[[main]]
name = "Forms"
pageRef = "forms"
weight = 40

[[main]]
name = "More"
weight = 100

[[main]]
name = "Show Schedule"
parent = "More"
pageRef = "show-schedule"
weight = 10

[[main]]
name = "Sponsors"
parent = "More"
pageRef = "sponsors"
weight = 20

[[main]]
name = "Rules and Bylaws"
parent = "More"
pageRef = "rules-and-bylaws"
weight = 30

[[main]]
name = "Results"
parent = "More"
pageRef = "results"
weight = 40

[[main]]
name = "Score Sheets"
parent = "More"
pageRef = "score-sheets"
weight = 50

[[main]]
name = "Green Rancher & Novice Youth"
parent = "More"
pageRef = "green-rancher-novice-youth"
weight = 60

[[main]]
name = "Year End Standings"
parent = "More"
pageRef = "year-end-standings"
weight = 70

[[main]]
name = "About"
parent = "More"
pageRef = "about"
weight = 80

[[main]]
name = "Contact"
parent = "More"
pageRef = "contact"
weight = 90

[[main]]
name = "Board of Directors"
parent = "More"
pageRef = "board-of-directors"
weight = 100

[[main]]
name = "Trainers Directory"
parent = "More"
pageRef = "trainers-directory"
weight = 110


#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
